# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: munic/type/utils/boxed.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "munic.type.utils.Boolean" do
    optional :value, :bool, 1
  end
  add_message "munic.type.utils.Integer" do
    optional :value, :int64, 1
  end
  add_message "munic.type.utils.Double" do
    optional :value, :double, 1
  end
  add_message "munic.type.utils.String" do
    optional :value, :string, 1
  end
  add_message "munic.type.utils.Bytes" do
    optional :value, :bytes, 1
  end
end

module Munic
  module Type
    module Utils
      Boolean = Google::Protobuf::DescriptorPool.generated_pool.lookup("munic.type.utils.Boolean").msgclass
      Integer = Google::Protobuf::DescriptorPool.generated_pool.lookup("munic.type.utils.Integer").msgclass
      Double = Google::Protobuf::DescriptorPool.generated_pool.lookup("munic.type.utils.Double").msgclass
      String = Google::Protobuf::DescriptorPool.generated_pool.lookup("munic.type.utils.String").msgclass
      Bytes = Google::Protobuf::DescriptorPool.generated_pool.lookup("munic.type.utils.Bytes").msgclass
    end
  end
end
