# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: munic/type/ack.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "munic.type.Ack" do
    optional :channel, :string, 1
    optional :status, :enum, 2, "munic.type.Ack.Code"
  end
  add_enum "munic.type.Ack.Code" do
    value :UNKNOWN, 0
    value :OK, 1
    value :NO_LISTENER, 2
    value :NOT_UNDERSTOOD, 3
  end
end

module Munic
  module Type
    Ack = Google::Protobuf::DescriptorPool.generated_pool.lookup("munic.type.Ack").msgclass
    Ack::Code = Google::Protobuf::DescriptorPool.generated_pool.lookup("munic.type.Ack.Code").enummodule
  end
end
