# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: munic/type/entity.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "munic.type.Entity" do
    oneof :entityType do
      optional :asset, :message, 1, "munic.type.Asset"
      optional :agentVersion, :message, 2, "munic.type.AgentVersion"
      optional :bsEntrypoint, :message, 3, "munic.type.BSEntrypoint"
    end
  end
  add_message "munic.type.Asset" do
    optional :id, :string, 1
    optional :account, :string, 2
  end
  add_message "munic.type.AgentVersion" do
    optional :id, :string, 1
    optional :version, :string, 2
    optional :agent, :message, 3, "munic.type.AgentVersion.Agent"
  end
  add_message "munic.type.AgentVersion.Agent" do
    optional :id, :string, 1
    optional :name, :string, 2
  end
  add_message "munic.type.BSEntrypoint" do
    optional :id, :string, 1
  end
end

module Munic
  module Type
    Entity = Google::Protobuf::DescriptorPool.generated_pool.lookup("munic.type.Entity").msgclass
    Asset = Google::Protobuf::DescriptorPool.generated_pool.lookup("munic.type.Asset").msgclass
    AgentVersion = Google::Protobuf::DescriptorPool.generated_pool.lookup("munic.type.AgentVersion").msgclass
    AgentVersion::Agent = Google::Protobuf::DescriptorPool.generated_pool.lookup("munic.type.AgentVersion.Agent").msgclass
    BSEntrypoint = Google::Protobuf::DescriptorPool.generated_pool.lookup("munic.type.BSEntrypoint").msgclass
  end
end
