# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: munic/type/message.proto

require 'google/protobuf'

require 'google/protobuf/timestamp_pb'
require 'google/type/latlng_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "munic.type.Message" do
    optional :channel, :string, 1
    optional :payload, :bytes, 2
    optional :want_ack, :bool, 3
    optional :timeout_at, :message, 4, "google.protobuf.Timestamp"
    optional :position, :message, 5, "google.type.LatLng"
  end
end

module Munic
  module Type
    Message = Google::Protobuf::DescriptorPool.generated_pool.lookup("munic.type.Message").msgclass
  end
end
