# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: munic/internals/type/eventMetadata.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "munic.internals.type.EventMetadata" do
    optional :previousRecord, :message, 1, "munic.internals.type.KafkaRecord"
  end
  add_message "munic.internals.type.KafkaRecord" do
    optional :key, :bytes, 1
    optional :topic, :string, 2
    optional :partition, :int32, 3
    optional :offset, :int64, 4
  end
end

module Munic
  module Internals
    module Type
      EventMetadata = Google::Protobuf::DescriptorPool.generated_pool.lookup("munic.internals.type.EventMetadata").msgclass
      KafkaRecord = Google::Protobuf::DescriptorPool.generated_pool.lookup("munic.internals.type.KafkaRecord").msgclass
    end
  end
end
