# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: munic/grpc/agent.proto for package 'munic.grpc'

require 'grpc'
require 'munic/grpc/agent_pb'

module Munic
  module Grpc
    module ProcessService
      # If the call to Process() returns without error, the sent events are
      # considered to have been processed successfully and are acknowledged
      class Service

        include GRPC::GenericService

        self.marshal_class_method = :encode
        self.unmarshal_class_method = :decode
        self.service_name = 'munic.grpc.ProcessService'

        rpc :Process, ProcessRequest, ProcessResponse
      end

      Stub = Service.rpc_stub_class
    end
  end
end
