# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: munic/grpc/agent.proto

require 'google/protobuf'

require 'munic/type/event_pb'
require 'google/protobuf/timestamp_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "munic.grpc.ProcessRequest" do
    optional :key, :message, 1, "munic.type.GroupKey"
    optional :is_deadline, :bool, 2
    optional :state, :message, 3, "munic.grpc.State"
    repeated :events, :message, 4, "munic.type.Event"
  end
  add_message "munic.grpc.ProcessResponse" do
    optional :state, :message, 1, "munic.grpc.State"
  end
  add_message "munic.grpc.State" do
    optional :bytes, :bytes, 1
    optional :deadline, :message, 2, "google.protobuf.Timestamp"
  end
end

module Munic
  module Grpc
    ProcessRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("munic.grpc.ProcessRequest").msgclass
    ProcessResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("munic.grpc.ProcessResponse").msgclass
    State = Google::Protobuf::DescriptorPool.generated_pool.lookup("munic.grpc.State").msgclass
  end
end
